### ISSUE TITLE
Passing really long query strings with lots of URLs (or fewer really long URLs) causes HTTP 400 errors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/embedly-proxy#10]
### Steps to reproduce:
1. Call the proxy with an offensively long list of URLs:

http://embedly-proxy.dev.mozaws.net/extract?urls=http%3A%2F%2Fideatown.dev%3A8000%2F&urls=http%3A%2F%2Flocalhost%3A1963%2Factivity-streams.html&urls=http%3A%2F%2Fidea-town-dev.elasticbeanstalk.com%2F...

### Actual results:
> ***Bad Request***
> Request Line is too large (5966 > 4094)

**Comment by jaredkerim** [comment]
This is being rejected by nginx, however we should not be sending long URL requests to the server.  The client should be responsible for splitting very large requests into multiple server requests.  URLs should be passed in through a POST body #1  The server will soon accept a maximum number of URLs or report an error otherwise #21 Closing this.
